package group34v2.ui;

import group34v2.Stop;
import group34v2.TimeHelper;
import group34v2.Util;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Victoria
 */
public class StopClient extends javax.swing.JFrame {
    StopLogin sl;
    /**
     * Creates new form StopClient
     */
    public StopClient() {
        doInBackground();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        statuPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        routeLabel = new javax.swing.JLabel();
        trainLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        unitLabel = new javax.swing.JLabel();
        routeInfoLabel = new javax.swing.JLabel();
        trainInfoLabel = new javax.swing.JLabel();
        timeInfoLabel = new javax.swing.JLabel();
        checkPanel = new javax.swing.JPanel();
        tipLabel = new javax.swing.JLabel();
        routeInfoBtn = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setText("UPCOMING");

        routeLabel.setText("Route");

        trainLabel.setText("NextStop");

        timeLabel.setText("Time Remaing");

        unitLabel.setText("   (HH:mm:ss)");

        routeInfoLabel.setText(routeID);

        trainInfoLabel.setText(nStop);

        timeInfoLabel.setText(tDiff);

        javax.swing.GroupLayout statuPanelLayout = new javax.swing.GroupLayout(statuPanel);
        statuPanel.setLayout(statuPanelLayout);
        statuPanelLayout.setHorizontalGroup(
            statuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel)
                    .addGroup(statuPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(statuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(statuPanelLayout.createSequentialGroup()
                                .addComponent(timeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(timeInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(statuPanelLayout.createSequentialGroup()
                                .addGroup(statuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(trainLabel)
                                    .addComponent(routeLabel))
                                .addGap(18, 18, 18)
                                .addGroup(statuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(routeInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(trainInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(unitLabel))
                .addContainerGap())
        );
        statuPanelLayout.setVerticalGroup(
            statuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statuPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(statuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(routeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(routeInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(statuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(trainLabel)
                    .addComponent(trainInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(statuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeLabel)
                    .addComponent(timeInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unitLabel)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        tipLabel.setText("For more specific Route Info:");

        routeInfoBtn.setText("Route Info");
        routeInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routeInfoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout checkPanelLayout = new javax.swing.GroupLayout(checkPanel);
        checkPanel.setLayout(checkPanelLayout);
        checkPanelLayout.setHorizontalGroup(
            checkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkPanelLayout.createSequentialGroup()
                .addGroup(checkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tipLabel))
                    .addGroup(checkPanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(routeInfoBtn)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        checkPanelLayout.setVerticalGroup(
            checkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkPanelLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(tipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(routeInfoBtn)
                .addGap(39, 39, 39))
        );

        backButton.setText("back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(statuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backButton)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(checkPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu.setText("StopClient");

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        menu.add(aboutMenuItem);

        exitMenuItem.setText("Exit");
        exitMenuItem.setToolTipText("Quit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        menu.add(exitMenuItem);

        menuBar.add(menu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        new About(this).setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        new StopLogin().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void routeInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeInfoBtnActionPerformed
//        this.setVisible(false);
        new RouteInfo().setVisible(true);
    }//GEN-LAST:event_routeInfoBtnActionPerformed

//    算法做的不太好,后期改进吧,先用笨方法完成
//    public void doInBackground()
//    {
//        Stop s;
//        ArrayList<String> timeheap = new ArrayList<String>();
//        for(Object obj : new Util().getObj("/stop/" + stopID + "/"))
//        {
//            s = (Stop) obj;
//            int idx = s.getStops().indexOf(stopID);
//            if (idx+1 < s.getStops().size())
//                timeheap.add(s.getTimes().get(idx+1));
//            else
//                continue;
//        }
//        
//        int len = timeheap.size();
//        int i = 0;
//        
//        while (timeheap.size() > 1)
//        {
//            if ( TimeHelper.calcTimeSimple(new Date().toString(), timeheap.get(i))
//                    && TimeHelper.calcTimeSimple(new Date().toString(), timeheap.get(i+1)))
//            {
//                if ( TimeHelper.calcTimeSimple(timeheap.get(i), timeheap.get(i+1))) {
//                    timeheap.remove(i+1);
//                } else {
//                    timeheap.remove(i);
//                }
//            }
//            else if ( TimeHelper.calcTimeSimple(new Date().toString(), timeheap.get(i)))
//            {
//                timeheap.remove(i+1);
//            }
//            else if ( TimeHelper.calcTimeSimple(new Date().toString(), timeheap.get(i+1)))
//            {
//                timeheap.remove(i);
//            }
//        }
//        
//        setTimeDiff(timeheap.get(0));
//        
//        for(Object obj : new Util().getObj("/stop/" + stopID + "/"))
//        {
//            s = (Stop) obj;
//            int idx = s.getStops().indexOf(stopID);
//            if ((idx+1) < s.getStops().size())
//                if (s.getTimes().get(idx+1) == tDiff)
//                    setNextStop(s.getStops().get(idx+1));
//                    setRouteID(s.getRouteID());
//        }
//    }
    
    public void doInBackground()
    {
        ArrayList<String> info = new ArrayList<String>();
        for (Object obj : new Util().getObj("/stop_tmp/"))
        {
            info = (ArrayList) obj;
            stopID = info.get(0);
            routeID = info.get(1);
            nStop = info.get(2);
            tDiff = info.get(3);
        }
        new File("./data/stop_tmp/" + stopID).delete();
    }
    
    public String getStopID() { return stopID; }
    public String getRouteID() { return routeID; }
    public String getNextStop() { return nStop; }
    public String getTimeDiff() { return tDiff; }
    
    public void setStopID(String value) { stopID = value; }
    public void setRouteID(String value) { routeID = value; }
    public void setNextStop(String value) { nStop = value; }
    public void setTimeDiff( String value) { tDiff = value; }
    
    private String stopID = null;
    private String routeID = null;
    private String nStop = null;
    private String tDiff = null;
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StopClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StopClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StopClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StopClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StopClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel checkPanel;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton routeInfoBtn;
    private javax.swing.JLabel routeInfoLabel;
    private javax.swing.JLabel routeLabel;
    private javax.swing.JPanel statuPanel;
    private javax.swing.JLabel timeInfoLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel tipLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel trainInfoLabel;
    private javax.swing.JLabel trainLabel;
    private javax.swing.JLabel unitLabel;
    // End of variables declaration//GEN-END:variables
}
