package code.ui;

import code.Util;
import java.io.File;
import java.nio.file.Paths;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Victoria
 */
public class TrainClient extends javax.swing.JFrame {

    /**
     * Creates new form TrainClient
     */
    public TrainClient(String trainID, String nStop, String tDiff) {
        this.trainID = trainID;
        this.nStop = nStop;
        this.tDiff = tDiff;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        trainClientPanel1 = new javax.swing.JPanel();
        trainIdLabel1 = new javax.swing.JLabel();
        nextStopLabel1 = new javax.swing.JLabel();
        timeRemainingLabel1 = new javax.swing.JLabel();
        backButton1 = new javax.swing.JButton();
        tidLabel = new javax.swing.JLabel();
        nstopLabel = new javax.swing.JLabel();
        tdiffLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        trainIdLabel1.setText("TrainID");

        nextStopLabel1.setText("Next Stop");

        timeRemainingLabel1.setText("Time Remaining");

        backButton1.setText("back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });

        tidLabel.setText(trainID);

        nstopLabel.setText(nStop);

        tdiffLabel.setText(tDiff);

        javax.swing.GroupLayout trainClientPanel1Layout = new javax.swing.GroupLayout(trainClientPanel1);
        trainClientPanel1.setLayout(trainClientPanel1Layout);
        trainClientPanel1Layout.setHorizontalGroup(
            trainClientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trainClientPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(trainClientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(trainIdLabel1)
                    .addComponent(nextStopLabel1)
                    .addComponent(timeRemainingLabel1))
                .addGroup(trainClientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(trainClientPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                        .addComponent(backButton1)
                        .addGap(22, 22, 22))
                    .addGroup(trainClientPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(trainClientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nstopLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tidLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tdiffLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        trainClientPanel1Layout.setVerticalGroup(
            trainClientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trainClientPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(trainClientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trainIdLabel1)
                    .addComponent(tidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(trainClientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextStopLabel1)
                    .addComponent(nstopLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(trainClientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeRemainingLabel1)
                    .addComponent(tdiffLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(backButton1)
                .addGap(21, 21, 21))
        );

        menu.setText("TrainClient");

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        menu.add(aboutMenuItem);

        exitMenuItem.setText("Exit");
        exitMenuItem.setToolTipText("Quit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        menu.add(exitMenuItem);

        menuBar.add(menu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(trainClientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(trainClientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        new About(this).setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        this.setVisible(false);
        new TrainLogin().setVisible(true);
    }//GEN-LAST:event_backButton1ActionPerformed
    
    public String getTrainID() { return trainID; }
    public String getNextStop() { return nStop; }
    public String getTimeDiff() { return tDiff; }
    
    public void setTrainID(String value) { trainID = value; }
    public void setNextStop(String value) { nStop = value; }
    public void setTimeDiff(String value) { tDiff = value; }
    
    private String trainID = null;
    private String nStop = null;
    private String tDiff = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton backButton1;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel nextStopLabel1;
    private javax.swing.JLabel nstopLabel;
    private javax.swing.JLabel tdiffLabel;
    private javax.swing.JLabel tidLabel;
    private javax.swing.JLabel timeRemainingLabel1;
    private javax.swing.JPanel trainClientPanel1;
    private javax.swing.JLabel trainIdLabel1;
    // End of variables declaration//GEN-END:variables
    private String wd = Paths.get("").toAbsolutePath().toString().substring(0, 
            Paths.get("").toAbsolutePath().toString().indexOf("Tourist-Train-Manage-System"));
    private String root = wd + "Tourist-Train-Manage-System/project/data";
}
