package group34v2.ui;

import group34v2.Util;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Victoria
 */
public class ControlCenter extends javax.swing.JFrame {

    /**
     * Creates new form ControlCenter
     */
    public ControlCenter() {
        setText("");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        statusTitle = new javax.swing.JLabel();
        routeTitle = new javax.swing.JLabel();
        trainTitle = new javax.swing.JLabel();
        driverTitle = new javax.swing.JLabel();
        stateTitle = new javax.swing.JLabel();
        scrollPanel = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        ctrlBtnPanel = new javax.swing.JPanel();
        addDriverBtn = new javax.swing.JButton();
        addTrainBtn = new javax.swing.JButton();
        addRouteBtn = new javax.swing.JButton();
        delDriverBtn = new javax.swing.JButton();
        delTrainBtn = new javax.swing.JButton();
        delRouteBtn = new javax.swing.JButton();
        sidebarBtnPanel = new javax.swing.JPanel();
        ckDriverBtn = new javax.swing.JButton();
        ckTrainBtn = new javax.swing.JButton();
        ckRouteBtn = new javax.swing.JButton();
        assignDriverBtn = new javax.swing.JButton();
        assignTrainBtn = new javax.swing.JButton();
        stopTrainBtn = new javax.swing.JButton();
        startTrainBtn = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        homeMenuBar = new javax.swing.JMenuBar();
        homeMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        statusTitle.setText("LIVE STATUS");

        routeTitle.setText("Running Routes");

        trainTitle.setText("Running Train");

        driverTitle.setText("Ongoing Driver");

        stateTitle.setText("Running State (Stoped)");

        textArea.setColumns(20);
        textArea.setRows(5);
        textArea.setText(text);
        scrollPanel.setViewportView(textArea);

        ctrlBtnPanel.setLayout(new java.awt.GridLayout(2, 0));

        addDriverBtn.setText("Add Driver");
        addDriverBtn.setPreferredSize(new java.awt.Dimension(100, 40));
        addDriverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDriverBtnActionPerformed(evt);
            }
        });
        ctrlBtnPanel.add(addDriverBtn);

        addTrainBtn.setText("Add Train");
        addTrainBtn.setPreferredSize(new java.awt.Dimension(100, 30));
        addTrainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTrainBtnActionPerformed(evt);
            }
        });
        ctrlBtnPanel.add(addTrainBtn);

        addRouteBtn.setText("Add Route");
        addRouteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRouteBtnActionPerformed(evt);
            }
        });
        ctrlBtnPanel.add(addRouteBtn);

        delDriverBtn.setText("Delete Driver");
        delDriverBtn.setPreferredSize(new java.awt.Dimension(100, 40));
        delDriverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delDriverBtnActionPerformed(evt);
            }
        });
        ctrlBtnPanel.add(delDriverBtn);

        delTrainBtn.setText("Delete Train");
        delTrainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delTrainBtnActionPerformed(evt);
            }
        });
        ctrlBtnPanel.add(delTrainBtn);

        delRouteBtn.setText("Delete Route");
        delRouteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delRouteBtnActionPerformed(evt);
            }
        });
        ctrlBtnPanel.add(delRouteBtn);

        sidebarBtnPanel.setLayout(new java.awt.GridLayout(7, 1));

        ckDriverBtn.setText("Check Driver");
        ckDriverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckDriverBtnActionPerformed(evt);
            }
        });
        sidebarBtnPanel.add(ckDriverBtn);

        ckTrainBtn.setText("Check Train");
        ckTrainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckTrainBtnActionPerformed(evt);
            }
        });
        sidebarBtnPanel.add(ckTrainBtn);

        ckRouteBtn.setText("Check Route");
        ckRouteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckRouteBtnActionPerformed(evt);
            }
        });
        sidebarBtnPanel.add(ckRouteBtn);

        assignDriverBtn.setText("Assign Driver");
        assignDriverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignDriverBtnActionPerformed(evt);
            }
        });
        sidebarBtnPanel.add(assignDriverBtn);

        assignTrainBtn.setText("Assign Train");
        assignTrainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignTrainBtnActionPerformed(evt);
            }
        });
        sidebarBtnPanel.add(assignTrainBtn);

        stopTrainBtn.setText("Stop Train");
        stopTrainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopTrainBtnActionPerformed(evt);
            }
        });
        sidebarBtnPanel.add(stopTrainBtn);

        startTrainBtn.setText("Start Train");
        startTrainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTrainBtnActionPerformed(evt);
            }
        });
        sidebarBtnPanel.add(startTrainBtn);

        backButton.setText("back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ctrlBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                    .addComponent(statusTitle, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                        .addComponent(driverTitle)
                        .addGap(18, 18, 18)
                        .addComponent(trainTitle)
                        .addGap(18, 18, 18)
                        .addComponent(routeTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stateTitle))
                    .addComponent(scrollPanel))
                .addGap(43, 43, 43)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sidebarBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(statusTitle)
                .addGap(17, 17, 17)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trainTitle)
                    .addComponent(routeTitle)
                    .addComponent(driverTitle)
                    .addComponent(stateTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sidebarBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollPanel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(ctrlBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(backButton, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        homeMenu.setText("Control Center");

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        homeMenu.add(aboutMenuItem);

        exitMenuItem.setText("Exit");
        exitMenuItem.setToolTipText("Quit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        homeMenu.add(exitMenuItem);

        homeMenuBar.add(homeMenu);

        setJMenuBar(homeMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        new About(this).setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        new ManagerLogin().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void ckTrainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckTrainBtnActionPerformed
//        this.setVisible(false);
        new TrainInfo().setVisible(true);
    }//GEN-LAST:event_ckTrainBtnActionPerformed

    private void ckDriverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckDriverBtnActionPerformed
//        this.setVisible(false);
        new DriverInfo().setVisible(true);
    }//GEN-LAST:event_ckDriverBtnActionPerformed

    private void ckRouteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckRouteBtnActionPerformed
//        this.setVisible(false);
        new RouteInfo().setVisible(true);
    }//GEN-LAST:event_ckRouteBtnActionPerformed

    private void addRouteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRouteBtnActionPerformed
        this.setVisible(false);
        dispose();
        new AddRoute().setVisible(true);
    }//GEN-LAST:event_addRouteBtnActionPerformed

    private void delRouteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delRouteBtnActionPerformed
        this.setVisible(false);
        dispose();
        new DelRoute().setVisible(true);
    }//GEN-LAST:event_delRouteBtnActionPerformed

    private void addTrainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTrainBtnActionPerformed
        this.setVisible(false);
        dispose();
        new AddTrain().setVisible(true);
    }//GEN-LAST:event_addTrainBtnActionPerformed

    private void addDriverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDriverBtnActionPerformed
        this.setVisible(false);
        dispose();
        new AddDriver().setVisible(true);
    }//GEN-LAST:event_addDriverBtnActionPerformed

    private void delDriverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delDriverBtnActionPerformed
        this.setVisible(false);
        dispose();
        new DelDriver().setVisible(true);
    }//GEN-LAST:event_delDriverBtnActionPerformed

    private void stopTrainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopTrainBtnActionPerformed
        this.setVisible(false);
        dispose();
        new StopTrain().setVisible(true);
    }//GEN-LAST:event_stopTrainBtnActionPerformed

    private void startTrainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTrainBtnActionPerformed
        this.setVisible(false);
        dispose();
        new StartTrain().setVisible(true);
    }//GEN-LAST:event_startTrainBtnActionPerformed

    private void assignDriverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignDriverBtnActionPerformed
        this.setVisible(false);
        dispose();
        new AssignDriver().setVisible(true);
    }//GEN-LAST:event_assignDriverBtnActionPerformed

    private void assignTrainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignTrainBtnActionPerformed
        this.setVisible(false);
        dispose();
        new AssignTrain().setVisible(true);
    }//GEN-LAST:event_assignTrainBtnActionPerformed

    private void delTrainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delTrainBtnActionPerformed
        this.setVisible(false);
        dispose();
        new DelTrain().setVisible(true);
    }//GEN-LAST:event_delTrainBtnActionPerformed
    
    public void setText(String value)
    {
        ArrayList list = new Util().readDir("/driver/");
        
        for (Object obj : list)
        {
            value = value + obj + "\n";
        }
        
        text = value;
    }
    
    private String text;
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlCenter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton addDriverBtn;
    private javax.swing.JButton addRouteBtn;
    private javax.swing.JButton addTrainBtn;
    private javax.swing.JButton assignDriverBtn;
    private javax.swing.JButton assignTrainBtn;
    private javax.swing.JButton backButton;
    private javax.swing.JButton ckDriverBtn;
    private javax.swing.JButton ckRouteBtn;
    private javax.swing.JButton ckTrainBtn;
    private javax.swing.JPanel ctrlBtnPanel;
    private javax.swing.JButton delDriverBtn;
    private javax.swing.JButton delRouteBtn;
    private javax.swing.JButton delTrainBtn;
    private javax.swing.JLabel driverTitle;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu homeMenu;
    private javax.swing.JMenuBar homeMenuBar;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel routeTitle;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JPanel sidebarBtnPanel;
    private javax.swing.JButton startTrainBtn;
    private javax.swing.JLabel stateTitle;
    private javax.swing.JLabel statusTitle;
    private javax.swing.JButton stopTrainBtn;
    private javax.swing.JTextArea textArea;
    private javax.swing.JLabel trainTitle;
    // End of variables declaration//GEN-END:variables
}
